[tools]
hk = "1.40.0"
pinact = "3.9.0"
pkl = "0.31.1"
zig = "0.15.2"
zizmor = "1.23.1"
action-validator = "0.8.0"
actionlint = "1.7.11"
"pipx:bump-my-version" = "1.3.0"
"pipx:mdformat" = { version = "1.0.0", uvx_args = "--with mdformat-gfm", pipx_args = "--preinstall mdformat-gfm" }
taplo = "0.10.0"
